### ISSUE TITLE
Thank You ❤️ 

### ISSUE THREAD

**Issue by Faisal50x** [imandolatkia/FullScreenCardViewPager_Android#3]
I came from your email, You send me a greeting and I  received it. 

Thank you for Emailing me, this nice Library that you made. I appreciate your work, I hope you will do more beautiful work in feature that helps thousands of people. 

A BIG thanks to you and those who work to help someone by making open-source projects.

**Comment by imandolatkia** [comment]
Hi @Faisal50x ,
Thank you for your support, I'm so happy that you like it.
I'm waiting for your precious opinions or pull requests.
